modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/yourname/socialmedia/issues"

[[mods]]
modId="socialmedia"
version="1.0.0"
displayName="Social Media Mod"
description='''
Minecraft için sosyal medya modu
'''
authors="YSFEYMYZC"
displayURL="https://github.com/yourname/socialmedia"

[[dependencies.socialmedia]]
modId="forge"
mandatory=true
versionRange="[51.0.33,)"
ordering="NONE"
side="BOTH"

[[dependencies.socialmedia]]
modId="minecraft"
mandatory=true
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
