name: Forge Mod Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Reponu klonla
      uses: actions/checkout@v4

      name: Make gradlew executable
      run: chmod +x gradlew

    - name: Java 21 kur
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Derle (gradlew build)
      run: ./gradlew build

    - name: Çıktıyı Kaydet (Artifacts)
      uses: actions/upload-artifact@v4
      with:
        name: SosyalMedyaMod
        path: build/libs/*.jar
